### ISSUE TITLE
AttributeError: 'Monster' object has no attribute '_absorb'

### ISSUE THREAD

**Issue by rsanchezgarc** [matteoferla/Fragmenstein#7]
It seems that an undefined method is tried to be called. I founded when I tried to combine the following molecules (of course, they have too many *, it  was a bug, but still, it was able to find a corner case)

['*c1ccc(F)c(*)c1', '*C(C)=O', '*N*', '*N*', '*c1ncc[nH]1', '*c1cccs1', '*N*', '*C(=O)O', '*C(C)=O', '*c1cccc(*)c1', '*C(N)=O']

Traceback (most recent call last):
  File "prueba.py", line 67, in <module>
    generated_molecule = compute(hits, split_bits=bool(i), randomize=i)
  File "prueba.py", line 61, in compute
    covalent_resn='CYS')
  File "/home/ruben/oxford/tools/Fragmenstein/fragmenstein/victor/_victor_automerge_mixin.py", line 108, in combine
    reject=self._reject)
  File "/home/ruben/oxford/tools/Fragmenstein/fragmenstein/victor/__init__.py", line 158, in _safely_do
    execute()
  File "/home/ruben/oxford/tools/Fragmenstein/fragmenstein/victor/_victor_automerge_mixin.py", line 124, in _combine_main
    self.monster.scaffold = self.monster.merge_hits(col_hits) #Here is where join_neighboring_mols can be reached
  File "/home/ruben/oxford/tools/Fragmenstein/fragmenstein/monster/__init__.py", line 421, in merge_hits
    scaffold = self.merge_pair(scaffold, fragmentanda)
  File "/home/ruben/oxford/tools/Fragmenstein/fragmenstein/monster/__init__.py", line 215, in merge_pair
    other_attachment_details=other_attachment_details)
  File "/home/ruben/oxford/tools/Fragmenstein/fragmenstein/monster/__init__.py", line 700, in _merge_part
    self._prevent_two_bonds_on_dummy(combo)
  File "/home/ruben/oxford/tools/Fragmenstein/fragmenstein/monster/__init__.py", line 453, in _prevent_two_bonds_on_dummy
    self._absorb(mol, atom.GetIdx(), second.GetIdx())
AttributeError: 'Monster' object has no attribute '_absorb'

**Comment by matteoferla** [comment]
Closing as `_absorb` was split into three:

* `_copy_bonding(mol, keeper, rejected)`
* `_mark_for_deletion(mol, rejected)`
* `_delete_marked(mol)`

and absorb is no longer called anywhere
